name: Manual
on:
    workflow_dispatch

jobs:
    run:
        runs-on: ubuntu-latest
        env:
            USERNAME: ${{ vars.USERNAME_TEST }}
        steps:
            - run: echo "${USERNAME_TEST}"