name: Manual
on:
    workflow_dispatch

jobs:
    run:
        if: ${{ github.actor == 'octocat' }}
        runs-on: ubuntu-latest
        steps:
            - run: exit 1
            - run: echo "Hello"
              if: ${{ failure() }}