name: Manual
run-name: Run by @${{ github.actor }}
on:
    workflow_dispatch

jobs:
    run:
        name: Super Useful Job
        runs-on: ubuntu-latest
        steps:
            - id: source
              run: echo "result=Hello" >> "${GITHUB_OUTPUT}"
            - env:
                RESULT: ${{ steps.source.outputs.result }}
              run: echo "${RESULT}"