name: Test
on:
    push

defaults:
    run:
        shell: bash

concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: true

jobs:
    # comment
    test:
        runs-on: ubuntu-latest
        steps:
            - run: echo "::debug::This is a debug log" # デバッグログ有効化時にのみ出力