name: Test
on:
    push

defaults:
    run:
        shell: bash

concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: true

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - run: | # マークダウンテキストをジョブサマリーへ出力
                echo "## Example Title:" >> "${GITHUB_STEP_SUMMARY}"
                echo "- first line" >> "${GITHUB_STEP_SUMMARY}"
                echo "- second line" >> "${GITHUB_STEP_SUMMARY}"