name: Test
on:
    push

defaults:
    run:
        shell: bash

concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: true

jobs:
    print:
        runs-on: ubuntu-latest
        environment: prod
        env:
            USERNAME: ${{ vars.USERNAME }}
            PASSWORD: ${{ secrets.PASSWORD }}
        steps:
            - run: echo "$USERNAME"
            - run: echo "$PASSWORD"